/**
 * types/index.ts
 *
 * Core domain and API type definitions for the Product Admin Dashboard.
 * Designed intentionally as flat, plain TypeScript interfaces (avoiding advanced
 * utility-type chains or complex generics) so they remain easily explainable
 * and predictable during live code walkthroughs.
 */

// Represents a user review attached to a product in DummyJSON
export interface Review {
  rating: number;
  comment: string;
  date: string;
  reviewerName: string;
  reviewerEmail: string;
}

// Represents physical dimensions of a product
export interface ProductDimensions {
  width: number;
  height: number;
  depth: number;
}

// Represents metadata such as timestamps and barcodes generated by the backend
export interface ProductMeta {
  createdAt: string;
  updatedAt: string;
  barcode: string;
  qrCode: string;
}

// Primary Product entity matching DummyJSON's full payload schema
export interface Product {
  id: number;
  title: string;
  description: string;
  category: string;
  price: number;
  discountPercentage?: number;
  rating: number;
  stock: number;
  tags?: string[];
  brand?: string;
  sku?: string;
  weight?: number;
  dimensions?: ProductDimensions;
  warrantyInformation?: string;
  shippingInformation?: string;
  availabilityStatus?: string;
  reviews?: Review[];
  returnPolicy?: string;
  minimumOrderQuantity?: number;
  meta?: ProductMeta;
  images: string[];
  thumbnail: string;
}

// Paginated response wrapper returned by DummyJSON /products endpoints
export interface ProductListResponse {
  products: Product[];
  total: number;
  skip: number;
  limit: number;
}

// User profile and authentication payload returned on successful login
export interface User {
  id: number;
  username: string;
  email: string;
  firstName: string;
  lastName: string;
  gender?: string;
  image?: string;
  token?: string;        // Compatibility for legacy DummyJSON auth response
  accessToken?: string;  // DummyJSON v2 auth token
  refreshToken?: string; // DummyJSON v2 refresh token
}

// Normalized application error structure used across all Axios calls and UI error states
export interface ApiError {
  message: string;
  status?: number;
  raw?: unknown;
}

// Payload contract for authentication login requests
export interface LoginCredentials {
  username: string;
  password: string;
  expiresInMins?: number;
}

// Category item representation from DummyJSON /products/categories
export interface CategoryItem {
  slug: string;
  name: string;
  url?: string;
}

// Supported sort fields for product catalog queries
export type SortField = "price" | "rating" | "title";

// Sort ordering direction
export type SortOrder = "asc" | "desc";
